version: '3.7'
services:
  database:
    image: postgres:latest
    container_name: db-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5441:5432'
  
  api:
    image: fabriciocruz/api-projeto-bom-samaritano:latest
    container_name: api-pbs
    depends_on:
      - database
    ports:
      - '8087:8087'
    working_dir: /app
    volumes:
      - ./api:/app
    command: npm start